<?php
session_start();

if (empty($_SESSION['user_id'])) {
    header('Location: index.html');
    exit;
}

require_once '../config.php';
require_once 'includes/permissions.php';
require_once 'includes/csrf.php';

function backup_redirect(string $message): void
{
    $_SESSION['backup_flash'] = [
        'type' => 'error',
        'message' => $message,
    ];
    header('Location: dashboard.php');
    exit;
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    backup_redirect('Use the dashboard backup button to generate a database export.');
}

if (!verify_csrf_token($_POST['csrf_token'] ?? null)) {
    backup_redirect('The backup request expired. Refresh the dashboard and try again.');
}

$userId = (int)$_SESSION['user_id'];
$permissions = get_user_permissions($conn, $userId);
if (!in_array('project_settings', $permissions, true)) {
    http_response_code(403);
    echo 'You do not have permission to download database backups.';
    exit;
}

$dbRow = $conn->query('SELECT DATABASE() AS db_name');
$dbName = $dbRow ? (string)($dbRow->fetch_assoc()['db_name'] ?? '') : '';
if ($dbName === '') {
    backup_redirect('The active database name could not be determined.');
}

function backup_identifier(string $value): string
{
    return '`' . str_replace('`', '``', $value) . '`';
}

function backup_literal(mysqli $conn, $value): string
{
    if ($value === null) {
        return 'NULL';
    }

    return "'" . $conn->real_escape_string((string)$value) . "'";
}

ignore_user_abort(true);
@set_time_limit(0);

while (ob_get_level() > 0) {
    ob_end_clean();
}

$safeDbName = preg_replace('/[^A-Za-z0-9_-]+/', '_', $dbName) ?: 'database';
$fileName = $safeDbName . '_backup_' . date('Ymd_His') . '.sql';

header('Content-Type: application/sql; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $fileName . '"');
header('Cache-Control: no-store, no-cache, must-revalidate');
header('Pragma: no-cache');

$out = fopen('php://output', 'wb');
if ($out === false) {
    backup_redirect('The backup stream could not be opened.');
}

fwrite($out, "-- Database backup generated by Construction Management\n");
fwrite($out, '-- Source database: ' . $dbName . "\n");
fwrite($out, '-- Generated at: ' . gmdate('Y-m-d H:i:s') . " UTC\n\n");
fwrite($out, "SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';\n");
fwrite($out, "SET AUTOCOMMIT = 0;\n");
fwrite($out, "START TRANSACTION;\n");
fwrite($out, "SET time_zone = '+00:00';\n");
fwrite($out, "SET NAMES utf8mb4;\n");
fwrite($out, 'CREATE DATABASE IF NOT EXISTS ' . backup_identifier($dbName) . " CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;\n");
fwrite($out, 'USE ' . backup_identifier($dbName) . ";\n");
fwrite($out, "SET foreign_key_checks = 0;\n\n");

$baseTables = [];
$views = [];
$tablesRes = $conn->query('SHOW FULL TABLES');
if (!$tablesRes) {
    fclose($out);
    backup_redirect('The database tables could not be read for backup.');
}

while ($row = $tablesRes->fetch_array(MYSQLI_NUM)) {
    $tableName = (string)($row[0] ?? '');
    $tableType = strtoupper((string)($row[1] ?? ''));
    if ($tableName === '') {
        continue;
    }

    if ($tableType === 'VIEW') {
        $views[] = $tableName;
        continue;
    }

    $baseTables[] = $tableName;
}
$tablesRes->close();

foreach ($baseTables as $tableName) {
    $quotedTable = backup_identifier($tableName);
    $createRes = $conn->query('SHOW CREATE TABLE ' . $quotedTable);
    if (!$createRes) {
        continue;
    }

    $createRow = $createRes->fetch_assoc();
    $createSql = (string)($createRow['Create Table'] ?? '');
    $createRes->close();

    fwrite($out, '-- Table structure for table ' . $quotedTable . "\n");
    fwrite($out, 'DROP TABLE IF EXISTS ' . $quotedTable . ";\n");
    fwrite($out, $createSql . ";\n\n");

    $dataRes = $conn->query('SELECT * FROM ' . $quotedTable, MYSQLI_USE_RESULT);
    if ($dataRes) {
        while ($row = $dataRes->fetch_assoc()) {
            $columns = [];
            $values = [];
            foreach ($row as $column => $value) {
                $columns[] = backup_identifier((string)$column);
                $values[] = backup_literal($conn, $value);
            }

            fwrite(
                $out,
                'INSERT INTO ' . $quotedTable . ' (' . implode(', ', $columns) . ') VALUES (' . implode(', ', $values) . ");\n"
            );
        }
        $dataRes->close();
    }

    fwrite($out, "\n");
}

foreach ($views as $viewName) {
    $quotedView = backup_identifier($viewName);
    $createRes = $conn->query('SHOW CREATE VIEW ' . $quotedView);
    if (!$createRes) {
        continue;
    }

    $createRow = $createRes->fetch_assoc();
    $createSql = (string)($createRow['Create View'] ?? '');
    $createRes->close();

    fwrite($out, '-- View structure for view ' . $quotedView . "\n");
    fwrite($out, 'DROP VIEW IF EXISTS ' . $quotedView . ";\n");
    fwrite($out, $createSql . ";\n\n");
}

$triggerRes = $conn->query('SHOW TRIGGERS');
if ($triggerRes) {
    while ($triggerRow = $triggerRes->fetch_assoc()) {
        $triggerName = (string)($triggerRow['Trigger'] ?? '');
        if ($triggerName === '') {
            continue;
        }

        $quotedTrigger = backup_identifier($triggerName);
        $createRes = $conn->query('SHOW CREATE TRIGGER ' . $quotedTrigger);
        if (!$createRes) {
            continue;
        }

        $createRow = $createRes->fetch_assoc();
        $createSql = (string)($createRow['SQL Original Statement'] ?? '');
        $timing = (string)($createRow['Timing'] ?? '');
        $event = (string)($createRow['Event'] ?? '');
        $table = (string)($createRow['Table'] ?? '');
        $createRes->close();

        if ($createSql === '' || $timing === '' || $event === '' || $table === '') {
            continue;
        }

        fwrite($out, '-- Trigger structure for trigger ' . $quotedTrigger . "\n");
        fwrite($out, 'DROP TRIGGER IF EXISTS ' . $quotedTrigger . ";\n");
        fwrite(
            $out,
            'CREATE TRIGGER ' . $quotedTrigger . ' ' . $timing . ' ' . $event . ' ON ' . backup_identifier($table) . ' FOR EACH ROW ' . $createSql . ";\n\n"
        );
    }
    $triggerRes->close();
}

fwrite($out, "SET foreign_key_checks = 1;\n");
fwrite($out, "COMMIT;\n");
fclose($out);
exit;